version: '3.1'
services:
  mariadb:
    container_name: "wmap_db"
    image: 'bitnami/mariadb:10.3'
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes

  web:
    container_name: "www_wmap"
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - mariadb
    volumes:
      - .:/www_wmap
    depends_on:
      - mariadb


volumes:
  mariadb_data:
    driver: local
