version: '2'
services:
  redis:
    container_name: "redis"
    image: redis:alpine
    restart: always
    volumes:
      - 'redis:/data'

  mariadb:
    container_name: "wmap_db"
    image: 'bitnami/mariadb:10.3'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/usr/local/var/mysql
    env_file:
      - .env

  web:
    container_name: "www_wmap"
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/www_wmap:cached
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - mariadb
      - redis
    volumes:
      - .:/www_wmap
    env_file:
      - .env

  postfix_587:
    hostname: "postfix"
    image: "boky/postfix"
    restart: always
    ports:
      - "1587:587"
    volumes:
      - "./test-keys:/etc/opendkim/keys"
    env_file:
      - .env

volumes:
  redis:
  my-db:
    external: false
