version: '3.7'
volumes:
  mariadb_data:
    driver: local
services:
  redis:
    container_name: "redis"
    image: redis:alpine
    restart: always
    command: redis-server
    ports:
      - "6379:6379"

  mariadb:
    container_name: "wmap_db"
    image: 'bitnami/mariadb:10.3'
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes

  web:
    container_name: "www_wmap"
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - mariadb
      - redis
      - sidekiq
    volumes:
      - .:/www_wmap
    depends_on:
      - mariadb
    environment:
      REDIS_URL: redis://redis:6379/0

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - redis
    volumes:
      - .:/www_wmap
    env_file:
      - .env
