## Authorizations
# Uncomment out the merging for each environment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# environment if you need something different per enviornment.
authorizations: &AUTHORIZATIONS
  allow_unauthenticated_bind: false
  group_base: ou=groups,dc=test,dc=com
  ## Requires config.ldap_check_group_membership in devise.rb be true
  # Can have multiple values, must match all to be authorized
  required_groups:
    # If only a group name is given, membership will be checked against "uniqueMember"
    - cn=admins,ou=groups,dc=test,dc=com
    - cn=users,ou=groups,dc=test,dc=com
    # If an array is given, the first element will be the attribute to check against, the second the group name
    - ["moreMembers", "cn=users,ou=groups,dc=test,dc=com"]
  ## Requires config.ldap_check_attributes in devise.rb to be true
  ## Can have multiple attributes and values, must match all to be authorized
  require_attribute:
    objectClass: inetOrgPerson
    authorizationRole: postsAdmin

## Environment

development:
  host: dc1.test.com
  port: 389
  attribute: sAMAccountName
  base: ou=groups,dc=test,dc=com
  admin_user: CN=wmap,CN=Users, ou=groups,dc=test,dc=com
  admin_password: QK@#$1_8ac
  ssl: false
  # <<: *AUTHORIZATIONS
  authorizations: &AUTHORIZATIONS
  #group_base: ou=role,dc=domain,dc=com
  required_groups:
    - ou=groups,dc=test,dc=com
  #require_attribute:
  #  memberOf: CN=CMBGroup,OU=New York Branch,DC=ny,DC=cmbchina,DC=com
    #memberOf: CN=Group_IT,OU=IT,OU=New York Branch,DC=ny,DC=cmbchina,DC=com


test:
  host: dc1.test.com
  port: 389
  attribute: sAMAccountName
  base: ou=groups, dc=test,dc=com
  admin_user: CN=wmap,CN=Users,ou=groups, dc=test,dc=com
  admin_password: QK@#$1_8ac
  ssl: false
  # <<: *AUTHORIZATIONS
  authorizations: &AUTHORIZATIONS
  #group_base: ou=role,dc=domain,dc=com
  required_groups:
    - ou=groups, dc=test,dc=com
  # <<: *AUTHORIZATIONS

production:
  host:  dc1.test.com
  port: 389
  attribute: sAMAccountName
  base: DC=us, DC=randomhouse, DC=com
  admin_user: <%= ENV['LDAP_SEEVICE_ACCT'] %>
  admin_password: <%= ENV['LDAP_SEEVICE_PASS'] %>
  ssl: false
  # <<: *AUTHORIZATIONS
  authorizations: &AUTHORIZATIONS
  #group_base: ou=role,dc=domain,dc=com
  required_groups:
    - ou=groups, dc=test,dc=com
