#---
:verbose: true
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:concurrency:  40
#---
:concurrency: 5
staging:
  :concurrency: 5
production:
  :verbose: false
  :concurrency: 5
:queues:
  - critical
  - default
  - low
  - mailers
